Controllers films users
MadraySha2/java-filmorate2 pull request #2
Opened 2023-02-17 20:11 UTC by MadraySha2

2023-02-19 08:11 UTC, TomattmanYandex requested changes
Привет, отличная работа, надо немного поправить но в основном мелочи

2023-02-19 08:11 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            return null;
чаще всего лучше вернуть пустой список чем null в данном контексте смысл примерно одинаковый, но если работать с пустым списком, то шанс ошибок гораздо меньше

2023-02-19 08:11 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        }
форматирование поехало

2023-02-19 08:11 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    int id;
во первых id мф не валидируем обычно, так как сами его проставляем
во вторых лучше использовать обертку вместо примитива, так появляется доп значение null которое значит что id еще не проставлен

2023-02-19 08:11 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
то же самое про примитивы и id

2023-02-19 08:11 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/validator/CorrectDate.java
> +public @interface CorrectDate {
очень круто
но на текущем уровне планировалось что если что то не можешь провалидировать аннотациями то просто будет метод validate который сделает проверки на валидацию, точнее наоборот даже, по умолчанию метод validate повышенная сложность аннотациии а это решение прям еще выше уровень, 
очень круто

2023-02-19 08:11 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    @Test
И снова, все очень круто, с другим подходом были бы другие тесты,
единственное что стоит исправить, обычно есть отдельные тесты под каждый случай,  один тестовый метод для проверки валидации длинны, следующий для проверки валидации описания, и т.д.

2023-02-19 08:11 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +    void getUserList() throws Exception {
тут та же самая ошибка

2023-02-19 09:21 UTC, MadraySha2 commented
Все поправил, а форматирование, похоже уже в гитхабе самом съезжает

2023-02-20 19:56 UTC, TomattmanYandex requested changes
надо минимально поправить

2023-02-20 19:56 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            return new ArrayList<>();
мне кажется отлично сработало бы 
просто return new ArrayList<>(filmsList.values());
если filmsList пустой, то values вернет пустой список тоже

2023-02-20 19:56 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Integer id;
ааа, потерял модификатор доступа

2023-02-20 20:06 UTC, MadraySha2 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            return new ArrayList<>();
Done ✅

2023-02-20 20:22 UTC, TomattmanYandex approved these changes
Принято

2023-02-20 21:42 UTC, merged